@startuml
    agent "PCT Organization" as pctorganization
    agent "HRex Organization" as hrexorganization
    agent "US Core Organization" as uscoreorganization
    agent "PCT Practitioner" as pctpractitioner
    agent "US Core Practitioner" as uscorepractitioner
    agent "PCT Coverage" as pctcoverage
    agent "US Core Coverage" as uscorecoverage
    agent "US Core Patient" as uscorepatient
    agent "Advanced Explanation of Benefits" as aeob
    agent "Good Faith Estimate" as gfe
	note bottom: professional or institutional
    uscorecoverage <|-- pctcoverage
    uscorepractitioner <|-- pctpractitioner
    uscoreorganization <|-- hrexorganization
    hrexorganization <|-- pctorganization
	aeob --> uscorepatient: "patient 1..1"
	aeob --> pctcoverage: "insurance.coverage 1..*"
	aeob --> pctpractitioner: "provider 1..1"
	aeob --> pctorganization: "provider 1..1"
	aeob --> pctorganization: "insurer 1..1"
	aeob --> gfe: "gfeReference 1..*"
@enduml
