# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.us.davinci-pct
canonical: http://hl7.org/fhir/us/davinci-pct
name: DaVinciPatientCostTransparency
title: DaVinci Patient Cost Transparency Implementation Guide
status: draft
version: 0.1.0
fhirVersion: 4.0.1
dependencies:
  hl7.fhir.us.core: 3.1.1

copyrightYear: 2021+
releaseLabel: ci-build
jurisdiction: urn:iso:std:iso:3166#US

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯

menu:
  
  Home: index.html

  Technical Background:       
    Relation to Other IGs: background.html#relation-to-other-IGs
    Underlying Technologies: underlying_technologies.html    
  
  Use Case:   
    Use Case: use_case.html#use-case 
    Create AEOB: use_case.html#submit-aeob-request-to-payer
    Get AEOB: use_case.html#get-completed-aeob-from-payer      
    System Actors: use_case.html#system-actors
    Terms and Concepts: use_case.html#terms-and-concepts
  
  Specification and Guidance:
    Specification: specification.html   
    General Guidance: general_guidance.html        
    Terminology Licensure: terminology_licensure.html
    Formal Specication: formal_specification.html 
  
  FHIR Artifacts:              
    Profiles: artifacts.html#1
    Extensions: artifacts.html#2
    Value Sets: artifacts.html#3
    Code Systems: artifacts.html#4   
    Examples: artifacts.html#5
    #Search Parameters: artifacts.html#6
    #Downloads: downloads.html#7

  Security:
    SMART on FHIR Application Launch (tentative): authorization_authentication_and_registration.html#smart-on-fhir-application-launch
    Authorization and Authentication: authorization_authentication_and_registration.html#authorization-and-authentication   
  
  Credits: credits.html