# TODO 
# Make sure all of the artifacts are in place and nicely organized
# Examples for all profiles
# Review all descriptions

# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.us.davinci-pct
canonical: http://hl7.org/fhir/us/davinci-pct
name: PatientCostTransparency
title: Patient Cost Transparency Implementation Guide
description: To support the request for cost information for specific services and items from the payer and return them in near real-time to allow effective decision making by the patient in consultation with the 'ordering' provider.
status: active
version: 2.0.0
extension:
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-wg  #<<< must include a http://hl7.org/fhir/StructureDefinition/structuredefinition-wg extension that identifies the workgroup responsible for the IG. This is the authoritative element.
    valueCode: fm  # <<< The value must be the code for the workgroup
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
    valueCode: trial-use
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm
    valueInteger: 2
# Maturity TBD
#  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm
#    valueInteger: 3
publisher:
  name: HL7 International / Financial Management
  url: http://www.hl7.org/Special/committees/fm
  email: fmlists@lists.hl7.org

fhirVersion: 4.0.1
dependencies:
  hl7.fhir.us.core:
    version: 7.0.0
    uri: http://hl7.org/fhir/us/core/ImplementationGuide/hl7.fhir.us.core
    id: uscore
    reason: |
      Needed for systems supporting USCDI v4
  hl7.fhir.us.core.v610:
    version: 6.1.0
    uri: http://hl7.org/fhir/us/core/v610/ImplementationGuide/hl7.fhir.us.core.v610
    id: uscore6
    reason: |
      Needed for systems supporting USCDI v3
  hl7.fhir.us.core.v311:
    version: 3.1.1
    uri: http://hl7.org/fhir/us/core/v311/ImplementationGuide/hl7.fhir.us.core.v311
    id: uscore3
    reason: |
      Needed for systems supporting USCDI v1
  hl7.fhir.extensions.r5: 5.2.0
  hl7.fhir.us.davinci-hrex: 
    version: 1.1.0
    uri: http://hl7.org/fhir/us/davinci-hrex/ImplementationGuide/hl7.fhir.us.davinci-hrex
    id: hrex
  hl7.terminology.r4:
    version: 6.5.0
    uri: http://terminology.hl7.org/ImplementationGuide/hl7.terminology
    id: tho
  hl7.fhir.uv.subscriptions-backport.r4: 1.1.0


copyrightYear: 2025+
releaseLabel: STU 2 - Draft
jurisdiction: urn:iso:std:iso:3166#US

parameters:   
  path-expansion-params: '../../input/exp-params.json'  # for using US ed of SNOMED
  active-tables: false
  apply-contact: true
  apply-jurisdiction: true
  apply-publisher: true
  apply-version: true
  show-inherited-invariants: false
  pin-canonicals: pin-multiples
  # usage-stats-opt-out: true
  # excludexml: false
  # excludejson: false
  # excludettl: true
  # excludemap: true
  # tabbed-snapshots: false
  # path-liquid: liquid
  #propagate-status: true
  auto-oid-root: 2.16.840.1.113883.4.642.40.4 
  version-comparison-master: 1.1.0
  version-comparison:
     - 1.0.0
     - 1.1.0


pages:
  index.md:
    title: Patient Cost Transparency Implementation Guide Home Page
    extension:
        - url: >-
            http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
          valueCode: informative
  reading_this_ig.md:
    title: Reading This IG
    extension:
        - url: >-
            http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
          valueCode: informative
  use_cases.md:
    title: Use Case and Actors
    extension:
        - url: >-
            http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
          valueCode: informative
  gfe_coordination_overview.md:
    title: Good Faith Estimate (GFE) Coordination Overview (Multi-Provider)
    extension:
        - url: >-
            http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
          valueCode: draft
  gfe_submission_and_aeob_overview.md:
    title: Good Faith Estimate (GFE) Submission and AEOB Overview
    extension:
        - url: >-
            http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
          valueCode: informative

  patient_access_support.md:
    title: Patient Access to GFE and AEOB
    extension:
        - url: >-
            http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
          valueCode: informative
  
  projects_and_participants.md:
    title: Project and Participants
    extension:
        - url: >-
            http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
          valueCode: trial-use
  formal_specification.md:
    title: Formal Specification
    extension:
        - url: >-
            http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
          valueCode: trial-use
  gfe_coordination_specification.md:
    title: Good Faith Estimate (GFE) Coordination Specification (Multi-Provider)
    extension:
        - url: >-
            http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
          valueCode: draft
  gfe_submission_and_aeob_specification.md:
    title: Good Faith Estimate (GFE) Submission and AEOB Specification
    extension:
        - url: >-
            http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
          valueCode: trial-use
  terminology_licensure.md:
    title: Terminology Licensure
    extension:
        - url: >-
            http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
          valueCode: informative
  security.md:
    title: Security
    extension:
        - url: >-
            http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
          valueCode: trial-use
  downloads.md:
    title: Downloads
    extension:
        - url: >-
            http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
          valueCode: informative
  change_log.md:
    title: Change Log
    extension:
        - url: >-
            http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
          valueCode: informative
#  credits.md:
#    title: Credits
  
  #artifacts.md:
  #  title: FHIR Artifacts

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯

menu:
  IG Home: index.html

  #Table of Contents: toc.html
  
  Background:
    Reading this IG: reading_this_ig.html
    Use Case and Actors: use_cases.html
    GFE Coordination Overview (Multi-Provider): gfe_coordination_overview.html
    GFE Submission and AEOB Overview: gfe_submission_and_aeob_overview.html
    Patient Access Support: patient_access_support.html
    Project and Participants: projects_and_participants.html
    

  Specification:
    Conformance Expectations: formal_specification.html
    GFE Coordination Specification (Multi-Provider): gfe_coordination_specification.html
    GFE Submission and AEOB Specification: gfe_submission_and_aeob_specification.html
    Privacy, Safety, and Security: security.html


  FHIR Artifacts:
    Capability Statements: artifacts.html#1
    Operations: artifacts.html#2
    Search Parameters: artifacts.html#3
    Profiles: artifacts.html#4
    Subscriptions: artifacts.html#7
    Extensions: artifacts.html#8
    Value Sets: artifacts.html#9
    Code Systems: artifacts.html#8
    Examples: artifacts.html#10
    Terminology Licensure: terminology_licensure.html

  Base Specs:
    FHIR R4 Spec: https://hl7.org/fhir/R4/
    HRex 1.1.0: https://hl7.org/fhir/us/davinci-hrex/STU1.1/
    US Core 7.0.0: https://hl7.org/fhir/us/core/STU7/
    US Core 6.1.0: https://hl7.org/fhir/us/core/STU6.1/
    US Core 3.1.1: https://hl7.org/fhir/us/core/STU3.1.1/
    Subscriptions Backport 1.1.0: https://hl7.org/fhir/uv/subscriptions-backport/STU1.1/



  Support:  
    Discussion Forum: https://chat.fhir.org/#narrow/stream/301151-Da-Vinci-PCT
    Project Page: https://confluence.hl7.org/spaces/DVP/pages/116460399/Patient+Cost+Transparency+PCT
    Implementer Support: https://confluence.hl7.org/spaces/DVP/pages/288396444/PCT+Implementer+Support
    Specification Dashboard: https://jira.hl7.org/secure/Dashboard.jspa?selectPageId=17111
    Propose a Change: https://jira.hl7.org/secure/CreateIssueDetails!init.jspa?pid=10405&amp;issuetype=10600&amp;customfield_11302=FHIR-us-davinci-pct
    Downloads: downloads.html
    


  Change Log: change_log.html
 
groups:
  CapabilityStatements:
    name: "Behavior: Capability Statements"
    description: The following artifacts define the specific capabilities that different types of systems are expected to have in order to comply with this implementation guide. Systems conforming to this implementation guide are expected to declare conformance to one or more of the following capability statements.
    resources:
    - CapabilityStatement/davinci-pct
    - CapabilityStatement/davinci-pct-coordination-platform
    - CapabilityStatement/davinci-pct-coordination-requester
    - CapabilityStatement/davinci-pct-gfe-contributor


  Operations:
    name: "Behavior: Operation Definitions"
    description: These are custom operations that can be supported by and/or invoked by systems conforming to this implementation guide.
    resources:
    - OperationDefinition/GFE-coordination-request
    - OperationDefinition/GFE-retrieve
    - OperationDefinition/GFE-submit

  SearchParameters:
    name: "Behavior: Search Parameters"
    description: These define the properties by which a RESTful server can be searched. They can also be used for sorting and including related resources.
    resources:
    - SearchParameter/aeob-date-of-service
    - SearchParameter/task-requested-period
    - SearchParameter/related-task

    - SearchParameter/DocumentReference-doc-status
    - SearchParameter/packet-condition
    - SearchParameter/packet-request-initiation-time
    - SearchParameter/packet-linking-identifier
    - SearchParameter/packet-PlannedPeriodOfService
    - SearchParameter/packet-procedure-or-service



  General:
    name: "Structures: General Resource Profiles"
    description: These define constraints on FHIR resources for systems conforming to this implementation guide.
    resources:
    - StructureDefinition/davinci-pct-organization
    - StructureDefinition/davinci-pct-practitioner
    - StructureDefinition/davinci-pct-coverage
    #- StructureDefinition/davinci-pct-self-pay-coverage

  GFE:
    name: "Structures: GFE Resource Profiles"
    description: These define constraints on GFE and GFE Coordination Request related FHIR resources for systems conforming to this implementation guide.
    resources:
    - StructureDefinition/davinci-pct-gfe-coordination-task
    - StructureDefinition/davinci-pct-gfe-contributor-task
    - StructureDefinition/davinci-pct-gfe-coordination-bundle
    - StructureDefinition/davinci-pct-gfe-information-bundle
    - StructureDefinition/davinci-pct-servicerequest
    - StructureDefinition/davinci-pct-medicationrequest
    - StructureDefinition/davinci-pct-devicerequest
    - StructureDefinition/davinci-pct-service-location
    #- StructureDefinition/davinci-pct-gfe-collection-bundle
    - StructureDefinition/davinci-pct-gfe-documentreference
    - StructureDefinition/davinci-pct-gfe-packet
    - StructureDefinition/davinci-pct-gfe-composition
    - StructureDefinition/davinci-pct-gfe-bundle
    - StructureDefinition/davinci-pct-gfe-missing-bundle
    - StructureDefinition/davinci-pct-gfe-summary
    - StructureDefinition/davinci-pct-gfe-institutional
    - StructureDefinition/davinci-pct-gfe-professional
    

  AEOB:
    name: "Structures: AEOB Resource Profiles"
    description: These define constraints on AEOB and GFE Submit related FHIR resources for systems conforming to this implementation guide.
    resources:
    - StructureDefinition/davinci-pct-aeob-documentreference
    - StructureDefinition/davinci-pct-aeob-packet
    - StructureDefinition/davinci-pct-aeob-composition
    - StructureDefinition/davinci-pct-aeob-summary
    - StructureDefinition/davinci-pct-aeob
    - StructureDefinition/davinci-pct-aeob-complete
    - StructureDefinition/davinci-pct-gfe-validation-error
    - StructureDefinition/davinci-pct-aeob-adjudication-error
    

  #ARCHIVED:
  #  name: "DO NOT USE: Archived Resource Profiles"
  #  description: These are archived profiles temporarily held during a transition from collection bundles to document bundles.
  #  resources:
  #  - StructureDefinition/davinci-pct-aeob-bundle
  #  - StructureDefinition/davinci-pct-gfe-collection-bundle

  Subscriptions:
    name: "Subscriptions"
    description: These define provide definitions for subscriptions including R4B based SubscriptionTopic and subscription profiles.
    resources:
    - SubscriptionTopic/davinci-pct-gfe-coordination-task-notification
    - SubscriptionTopic/davinci-pct-gfe-available-subject-notification
    - SubscriptionTopic/davinci-pct-gfe-available-author-notification
    - SubscriptionTopic/davinci-pct-aeob-available-subject-notification
    - SubscriptionTopic/davinci-pct-aeob-available-author-notification

    - StructureDefinition/davinci-pct-gfe-task-update-subscription
    - StructureDefinition/davinci-pct-gfe-available-subject-subscription
    - StructureDefinition/davinci-pct-gfe-available-author-subscription
    - StructureDefinition/davinci-pct-aeob-available-subject-subscription
    - StructureDefinition/davinci-pct-aeob-available-author-subscription
    


 # Base Specs:
 #   FHIR R4 Spec: new-tab {{site.data.fhir.path}}
 #   US Core: new-tab {{site.data.fhir.ver.hl7_fhir_us_core}}
 #   HRex: new-tab {{site.data.fhir.ver.hl7_fhir_us_davinci_hrex}}

 # History: http://hl7.org/fhir/us/davinci-pct/history.html
