# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.us.davinci-pct
canonical: http://hl7.org/fhir/us/davinci-pct
name: PatientCostTransparency
title: Patient Cost Transparency Implementation Guide
description: To support the request for cost information for specific services and items from the payer and return them in near real-time to allow effective decision making by the patient in consultation with the 'ordering' provider.
status: active
version: 2.0.0-ballot
extension:
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-wg  #<<< must include a http://hl7.org/fhir/StructureDefinition/structuredefinition-wg extension that identifies the workgroup responsible for the IG. This is the authoritative element.
    valueCode: fm  # <<< The value must be the code for the workgroup
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-standards-status
    valueCode: trial-use
# Maturity TBD
#  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-fmm
#    valueInteger: 3
publisher:
  name: HL7 International / Financial Management
  url: http://www.hl7.org/Special/committees/fm
  email: fmlists@lists.hl7.org

fhirVersion: 4.0.1
dependencies:
  hl7.fhir.us.core: 3.1.1
  hl7.fhir.extensions.r5: 4.0.1
  hl7.fhir.us.davinci-hrex: 1.0.0     # NOTE: Da Vinci HRex depends on US Core 3.1.0

copyrightYear: 2023+
releaseLabel: STU 2 Ballot
jurisdiction: urn:iso:std:iso:3166#US

parameters:   
  version-comparison-master: true
  show-inherited-invariants: false
  path-liquid: liquid
  #auto-oid-root=OID Goes here

pages:
  index.md:
    title: Patient Cost Transparency Implementation Guide Home Page
  use_cases.md:
    title: Use Cases and Overview
  underlying_technologies.md:
    title: Technical Background and Underlying Technologies
  formal_specification.md:
    title: Formal Specification
  gfe-request-specification.md:
    title: GFE Request Specification
  gfe-submit-specification.md:
    title: GFE Submit Specification
  terminology_licensure.md:
    title: Terminology Licensure
  security.md:
    title: Security
  downloads.md:
    title: Downloads
  change_log.md:
    title: Change Log
#  credits.md:
#    title: Credits
  
  #artifacts.md:
  #  title: FHIR Artifacts

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯

menu:
  IG Home: index.html

  Table of Contents: toc.html
  
  Background:
    Use Cases and Overview: use_cases.html
    Technical Background and Underlying Technologies: underlying_technologies.html

  Specification:
    Formal Specification: formal_specification.html
    GFE Request: gfe-request-specification.html
    GFE Submit: gfe-submit-specification.html


  FHIR Artifacts:
    Capability Statements: artifacts.html#1
    Operations: artifacts.html#2
    Search Parameters: artifacts.html#3
    Profiles: artifacts.html#4
    Extensions: artifacts.html#5
    Value Sets: artifacts.html#6
    Code Systems: artifacts.html#7
    Examples: artifacts.html#8
    Terminology Licensure: terminology_licensure.html
    
  Security: security.html
    
  Downloads: downloads.html
  
  Change Log: change_log.html
 
groups:
  CapabilityStatements:
    name: "Behavior: Capability Statements"
    description: The following artifacts define the specific capabilities that different types of systems are expected to have in order to comply with this implementation guide. Systems conforming to this implementation guide are expected to declare conformance to one or more of the following capability statements.
    resources:
    - CapabilityStatement/davinci-pct


  Operations:
    name: "Behavior: Operation Definitions"
    description: These are custom operations that can be supported by and/or invoked by systems conforming to this implementation guide.
    resources:
    - OperationDefinition/GFE-retrieve
    - OperationDefinition/GFE-submit

  SearchParameters:
    name: "Behavior: Search Parameters"
    description: These define the properties by which a RESTful server can be searched. They can also be used for sorting and including related resources.
    resources:
    - SearchParameter/aeob-date-of-service


  General:
    name: "Structures: General Resource Profiles"
    description: These define constraints on FHIR resources for systems conforming to this implementation guide.
    resources:
    - StructureDefinition/davinci-pct-organization
    - StructureDefinition/davinci-pct-practitioner
    - StructureDefinition/davinci-pct-coverage

  GFERequest:
    name: "Structures: GFE Resource Profiles"
    description: These define constraints on GFE and GFE Request related FHIR resources for systems conforming to this implementation guide.
    resources:
    - StructureDefinition/davinci-pct-coordinating-gfe-request-task
    - StructureDefinition/davinci-pct-gfe-provider-request-task
    - StructureDefinition/davinci-pct-gfe-request-bundle
    - StructureDefinition/davinci-pct-gfe-request-information-bundle
    - StructureDefinition/davinci-pct-proposed-servicerequest
    - StructureDefinition/davinci-pct-proposed-medicationrequest
    - StructureDefinition/davinci-pct-proposed-devicerequest
    - StructureDefinition/davinci-pct-gfe-collection-bundle
    - StructureDefinition/davinci-pct-gfe-bundle
    - StructureDefinition/davinci-pct-gfe-missing-bundle
    - StructureDefinition/davinci-pct-gfe-summary
    - StructureDefinition/davinci-pct-gfe-institutional
    - StructureDefinition/davinci-pct-gfe-professional
    - StructureDefinition/davinci-pct-gfe-validation-error

  AEOB:
    name: "Structures: AEOB Resource Profiles"
    description: These define constraints on AEOB and GFE Submit related FHIR resources for systems conforming to this implementation guide.
    resources:
    - StructureDefinition/davinci-pct-aeob-bundle
    - StructureDefinition/davinci-pct-aeob-summary
    - StructureDefinition/davinci-pct-aeob
    - StructureDefinition/davinci-pct-aeob-complete
    - StructureDefinition/davinci-pct-aeob-adjudication-error





 # Base Specs:
 #   FHIR R4 Spec: new-tab {{site.data.fhir.path}}
 #   US Core: new-tab {{site.data.fhir.ver.hl7_fhir_us_core}}
 #   HRex: new-tab {{site.data.fhir.ver.hl7_fhir_us_davinci_hrex}}

 # History: http://hl7.org/fhir/us/davinci-pct/history.html
