# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.us.davinci-pct
canonical: http://hl7.org/fhir/us/davinci-pct
name: PatientCostTransparency
title: Patient Cost Transparency Implementation Guide
description: To support the request for cost information for specific services and items from the payer and return them in near real-time to allow effective decision making by the patient in consultation with the 'ordering' provider.
status: active
version: 1.0.0
publisher:
  name: HL7 International - Financial Management Work Group
  url: http://hl7.org/Special/committees/fm
  email: fmlists@lists.hl7.org

fhirVersion: 4.0.1
dependencies:
  hl7.fhir.us.core: 3.1.1
  hl7.fhir.us.davinci-hrex: 1.0.0     # NOTE: Da Vinci HRex depends on US Core 3.1.0

copyrightYear: 2023+
releaseLabel: STU 1
jurisdiction: urn:iso:std:iso:3166#US

parameters:   
  show-inherited-invariants: false

pages:
  index.md:
    title: Patient Cost Transparency Implementation Guide Home Page
  use_cases.md:
    title: Use Cases and Overview
  underlying_technologies.md:
    title: Technical Background and Underlying Technologies
  formal_specification.md:
    title: Formal Specification
  terminology_licensure.md:
    title: Terminology Licensure
  security.md:
    title: Security
  downloads.md:
    title: Downloads
  change_log.md:
    title: Change Log
#  credits.md:
#    title: Credits
  
  #artifacts.md:
  #  title: FHIR Artifacts

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯

menu:
  IG Home: index.html

  Table of Contents: toc.html
  
  Background:
    Use Cases and Overview: use_cases.html
    Technical Background and Underlying Technologies: underlying_technologies.html

  Specification:
    Formal Specification: formal_specification.html    


  FHIR Artifacts:
    Capability Statements: artifacts.html#1
    Operations: artifacts.html#2
    Search Parameters: artifacts.html#3
    Profiles: artifacts.html#4
    Extensions: artifacts.html#5
    Value Sets: artifacts.html#6
    Code Systems: artifacts.html#7
    Examples: artifacts.html#8
    Terminology Licensure: terminology_licensure.html
    
  Security: security.html
    
  Downloads: downloads.html
  
  Change Log: change_log.html
 
 # Base Specs:
 #   FHIR R4 Spec: new-tab {{site.data.fhir.path}}
 #   US Core: new-tab {{site.data.fhir.ver.hl7_fhir_us_core}}
 #   HRex: new-tab {{site.data.fhir.ver.hl7_fhir_us_davinci_hrex}}

 # History: http://hl7.org/fhir/us/davinci-pct/history.html
