# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.us.davinci-pct
canonical: http://hl7.org/fhir/us/davinci-pct
name: DaVinciPatientCostTransparency
title: Da Vinci Patient Cost Transparency Implementation Guide
status: draft
version: 0.1.0
fhirVersion: 4.0.1
dependencies:
  hl7.fhir.us.core: 3.1.1

copyrightYear: 2021+
releaseLabel: ci-build
jurisdiction: urn:iso:std:iso:3166#US





pages:
  index.md:
    title: Patient Cost Transperency Implementation Guide Home Page
  use_cases.md:
    title: Use Cases and Overview
  underlying_technologies.md:
    title: Technical Background and Underlying Technologies
  formal_specification.md:
    title: Formal Specification
  #terminology_licensure.md:
  #  title: Terminology Licensure
  #downloads.md:
  #  title: Downloads
  credits.md:
    title: Credits
  #artifacts.md:
  #  title: FHIR Artifacts  

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯

menu: 
  
  Table of Contents: toc.html

  PCT Specification:
    PCT Home Page: index.html      
    Technical Background and Underlying Technologies: underlying_technologies.html          
    Relation to Other IGs: formal_specification.html#integration-with-other-implementation-guides  
    Use Cases and Overview: use_cases.html      
    Formal Specification: formal_specification.html 
    #Terminology Licensure: terminology_licensure.html   
    #Downloads: downloads.html
    Credits: credits.html
  
  FHIR Artifacts:              
    Profiles: artifacts.html#1
    Extensions: artifacts.html#2
    Value Sets: artifacts.html#3
    Code Systems: artifacts.html#4   
    Examples: artifacts.html#5   
    
  Base Specs:
    FHIR R4 Spec: new-tab {{site.data.fhir.path}}
    US Core: new-tab {{site.data.fhir.ver.hl7_fhir_us_core}}

  History: http://hl7.org/fhir/us/davinci-pct/history.html

  


  
  