//// US Core ////
Alias:   $USCoreLocation = http://hl7.org/fhir/us/core/StructureDefinition/us-core-location
Alias:   $USCorePatient = http://hl7.org/fhir/us/core/StructureDefinition/us-core-patient
Alias:   $USCorePractitioner = http://hl7.org/fhir/us/core/StructureDefinition/us-core-practitioner
Alias:   $USCorePractitionerRole = http://hl7.org/fhir/us/core/StructureDefinition/us-core-practitionerrole
Alias:   $USCoreOrganization = http://hl7.org/fhir/us/core/StructureDefinition/us-core-organization
Alias:   $USCoreProviderRole = http://hl7.org/fhir/us/core/ValueSet/us-core-provider-role
Alias:   $USCoreProviderSpecialty = http://hl7.org/fhir/us/core/ValueSet/us-core-provider-specialty

//// Code systems ////
Alias:   NUCC = http://nucc.org/provider-taxonomy
Alias:   $TAXCodeCS = urn:oid:2.16.840.1.113883.4.4
Alias:   $ClaimTypeCS = http://terminology.hl7.org/CodeSystem/claim-type
Alias:   $CMSPOSCS = https://www.cms.gov/Medicare/Coding/place-of-service-codes/Place_of_Service_Code_Set
Alias:   $ISO3166-P1-ALPHA2 = http://terminology.hl7.org/CodeSystem/iso3166-1edition2alpha2
Alias:   $ISO3166-P2-CSC = 	urn:iso:std:iso:3166:-2
Alias:   $CARETEAMROLECS = http://terminology.hl7.org/CodeSystem/claimcareteamrole
Alias:   $ContactPurposeCS = http://terminology.hl7.org/CodeSystem/contactentity-type
Alias:   $USNPI = http://hl7.org/fhir/sid/us-npi
Alias:   $TOBFL-04 = https://www.nubc.org/CodeSystem/TypeOfBill
Alias:   $CPT = http://www.ama-assn.org/go/cpt
Alias:   $HCPCS = http://www.cms.gov/Medicare/Coding/HCPCSReleaseCodeSets
Alias:   $HIPPS = https://www.cms.gov/Medicare/Medicare-Fee-for-Service-Payment/ProspMedicareFeeSvcPmtGen/HIPPSCodes
Alias:   $NDC = http://hl7.org/fhir/sid/ndc
Alias:   $V2-0203 = http://terminology.hl7.org/CodeSystem/v2-0203
Alias:   $DIAGTYPECS = http://terminology.hl7.org/CodeSystem/ex-diagnosistype
Alias:   $PROCTYPECS = http://terminology.hl7.org/CodeSystem/ex-procedure-type
Alias:   $ADJUDCS = http://terminology.hl7.org/CodeSystem/adjudication
Alias:   $ICD10CM = http://hl7.org/fhir/sid/icd-10-cm
Alias:   $ORGTYPE = http://terminology.hl7.org/CodeSystem/organization-type
Alias:   $PAYEETYPE = http://terminology.hl7.org/CodeSystem/payeetype
Alias:   $PROCPRIORITY = http://terminology.hl7.org/CodeSystem/processpriority
Alias:   $NUBCREVENUE = https://www.nubc.org/CodeSystem/RevenueCodes
Alias:   $CLAIMUSECS = http://hl7.org/fhir/claim-use
Alias:   $DAR = http://terminology.hl7.org/CodeSystem/data-absent-reason

//// Value Sets ////
Alias:   $IdentifierTypeVS   =  http://hl7.org/fhir/ValueSet/identifier-type
Alias:   $OrganizationType = http://hl7.org/fhir/ValueSet/organization-type
Alias:   $CoverageCopayTypeCodes = 	http://hl7.org/fhir/ValueSet/coverage-copay-type
//Alias:   $USCSPECIALTY = http://hl7.org/fhir/us/core/ValueSet/us-core-provider-specialty
Alias:   $USCPROCROLE = http://hl7.org/fhir/us/core/ValueSet/us-core-provider-role
Alias:   $ISO3166-P1-ALPHA2-VS = http://hl7.org/fhir/ValueSet/iso3166-1-2
Alias:   $ISO3166-P2-CSC-VS = http://terminology.hl7.org/ValueSet/v2-notAllCodes-0347
//Alias:   $REVENUEVS = http://hl7.org/fhir/ValueSet/ex-revenue-center
//Alias:   $ADJUDVS = http://hl7.org/fhir/ValueSet/adjudication
Alias:   $PROCPRIORITYVS = http://hl7.org/fhir/ValueSet/process-priority
Alias:   $AMACPTALL = http://hl7.org/fhir/ValueSet/cpt-all
Alias:   $CLAIMUSEVS = http://hl7.org/fhir/ValueSet/claim-use

//// CARIN-BB ////
Alias:   $AHANUBCRevenueCodes = http://hl7.org/fhir/us/carin-bb/ValueSet/AHANUBCRevenueCodes
Alias:   $AMACPTCMSHCPCSModifiers = http://hl7.org/fhir/us/carin-bb/ValueSet/AMACPTCMSHCPCSModifiers
Alias:   $C4BBEOBInstitutionalProcedureCodes = http://hl7.org/fhir/us/carin-bb/ValueSet/C4BBEOBInstitutionalProcedureCodes
Alias:   $C4BBAdjudication = http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBAdjudication
Alias:   $FDANationalDrugCode = http://hl7.org/fhir/us/carin-bb/ValueSet/FDANationalDrugCode
Alias:   $C4BBSupportingInfoType = http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBSupportingInfoType
Alias:   $C4BBSupportingInfoTypeVS = http://hl7.org/fhir/us/carin-bb/ValueSet/C4BBSupportingInfoType
Alias:   $AHANUBCTypeOfBill = http://hl7.org/fhir/us/carin-bb/ValueSet/AHANUBCTypeOfBill
